### ISSUE TITLE
Change the 'fixed' field to status

### ISSUE THREAD

**Issue by emiliorizzo** [coinspect/md-report-parser#1]
The findings 'fixed' field is a boolean.
We need to change it to a status field which allows different values.

**Comment by emiliorizzo** [comment]
Questions: @juli 

Field name?
Fixed list of values?
How should we render these values? 
(I think we need to extend the list of the 'status' icons)

**Comment by juli** [comment]
Field name: status
List of Values:
* Open
* Partially Fixed
* Fixed
* Acknowledged
* Deferred

And the visualization will reflect both total risk and current status:

High/Medium x Open -> X
High/Medium x  Partially Fixed -> !
High/Medium x Fixed -> √
High/Medium x Acknowledged -> !
High/Medium x Deferred -> !
Low x Open -> !
Low x Partially Fixed -> √
Low x Fixed -> √
Low x Acknowledged -> !
Low x Deferred -> !

The usual red, orange/yellow and green colors can be used for each of the symbols
